export {default as banner_img} from "./banner_img.png"
export {default as raeact_img} from "./react.png"
export {default as review_img} from "./Review.png"
export {default as videocall_img} from "./Video-call.png"
export {default as about_img} from "./about-img1.jpg"
export {default as second_img1} from "./about_img2.jpg"
export {default as service_img} from "./service_bg.jpg"
export {default as facility_management} from "./facility_management_service.jpg"
export {default as ship_management} from "./ship_management.jpg"
export {default as airport_management} from "./airport_management.jpg"
export {default as waste_management} from "./waste_management.jpg"
export {default as faq_img} from "./faq-img.jpg"
export {default as appointment_img} from "./appoinment_img.png"
export {default as appointment_bg} from "./appointment_bg.jpg"
export {default as slider1} from "./asian-male-plumber-uniform-talking-senior-female-homeowner-kitchen.jpg"
export {default as slider2} from "./images (1).jpg"
export {default as slider3} from "./factory-worker-wearing-uniform-hardhat-operating-industrial-machine-with-push-button-joystick-production-hall.jpg"
export {default as aboutus} from "./about_us_3.jpg"
export {default as ceo} from "./WhatsApp Image 2024-11-15 at 5.57.49 PM (1).jpeg"
export {default as md} from "./Madam.jpeg"
export {default as bd} from "./WhatsApp Image 2025-09-09 at 16.12.15.jpeg"
export {default as mm} from "./Niranjan.jpeg"
export {default as se} from "./house-keeping.8779bba1.jpg"
export {default as sm} from "./security.a9059eb9.jpg"
export {default as sl} from "./staffing.b9f6001b.jpg"
export {default as mobile} from "./Untitled_design-removebg-preview.png"
export {default as bc} from "./WhatsApp Image 2024-12-06 at 12.54.01_bcc8d9fa.jpg"
export {default as aboutusnew} from "./aboutpic.jpeg"
export {default as Pay} from "./payroll.png"
export {default as picture12} from "./payrollpicture1.png"
export {default as picture15} from "./wst.jpg"
export {default as picture20} from "./Santitizepic.jpeg"
